# Numpy Tutorial
## Course: ENGN/COMP8535 - Engineering Data Analytics
### Tutor: Evan Markou
#### Date : 02 March, 2022

---

#### Prerequisites: Basic knowledge of Python

---

[Numpy](http://www.numpy.org/) is the core Python package for numerical computing. The main features of Numpy are:

* $N$-dimensional array object `ndarray`
* Vectorized operations and functions which broadcast across arrays for fast computation

To get started with Numpy, let's adopt the standard convention and import it using the name `np`:

In [1]:
import numpy as np


## Numpy Arrays

The fundamental object provided by the Numpy package is the `ndarray`. We can think of a 1D (1-dimensional) `ndarray` as a list, a 2D (2-dimensional) `ndarray` as a matrix, a 3D (3-dimensional) `ndarray` as a 3-tensor, and so on. See the [Numpy tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html) for more about Numpy arrays.

---

### Creating Arrays

The function `numpy.array` creates a Numpy array from a Python sequence such as a list, a tuple or a list of lists. For example, create a 1D Numpy array from a Python list:

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Notice also that a Numpy array is displayed slightly differently when output by a cell (as opposed to being explicitly printed to output by the `print` function):

In [3]:
a

array([1, 2, 3, 4, 5])

Use the built-in function `type` to verify the type:

In [4]:
type(a)

numpy.ndarray

Create a 2D Numpy array from a Python list of lists:

In [5]:
M = np.array([[1,2,3],[4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


Create an $n$-dimensional Numpy array from nested Python lists. For example, the following is a 3D Numpy array:

In [6]:
N = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] , [[9,10],[11,12]] ])
print(N)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


There are several Numpy functions for [creating arrays](https://docs.scipy.org/doc/numpy/user/quickstart.html#array-creation):

| Function | Description |
| ---: | :--- |
| `numpy.array(a)` | Create $n$-dimensional NumPy array from sequence `a` |
| `numpy.linspace(a,b,N)` | Create 1D NumPy array with `N` equally spaced values from `a` to `b` (inclusively)|
| `numpy.arange(a,b,step)` | Create 1D NumPy array with values from `a` to `b` (exclusively) incremented by `step`|
| `numpy.zeros(N)` | Create 1D NumPy array of zeros of length $N$ |
| `numpy.zeros((n,m))` | Create 2D NumPy array of zeros with $n$ rows and $m$ columns |
| `numpy.ones(N)` | Create 1D NumPy array of ones of length $N$ |
| `numpy.ones((n,m))` | Create 2D NumPy array of ones with $n$ rows and $m$ columns |
| `numpy.eye(N)` | Create 2D NumPy array with $N$ rows and $N$ columns with ones on the diagonal (ie. the identity matrix of size $N$) |

Create a 1D Numpy array with 10 equally spaced values from 0 to 1:

In [7]:
x = np.linspace(0,1,10)
print(x)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Create a 1D Numpy array with values from 0 to 20 (exclusively) incremented by 2.5:

In [8]:
y = np.arange(0, 20, 2.5)
print(y)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


These are the functions that we'll use most often when creating Numpy arrays. The function `numpy.linspace` works best when we know the *number of points* we want in the array, and `numpy.arange` works best when we know *step size* between values in the array.

Create a 1D Numpy array of zeros of length 5:

In [9]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


Create a 2D Numpy array of zeros with 2 rows and 5 columns:

In [10]:
M = np.zeros((2,5))
print(M)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create a 1D Numpy array of ones of length 7:

In [11]:
w = np.ones(7)
print(w)

[1. 1. 1. 1. 1. 1. 1.]


Create a 2D Numpy array of ones with 3 rows and 2 columns:

In [12]:
N = np.ones((3,2))
print(N)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Create the identity matrix of size 10:

In [13]:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


---
### Dimension, Shape and Size

We can think of a 1D Numpy array as a list of numbers, a 2D Numpy array as a matrix, a 3D Numpy array as a tensor, and so on. Given a Numpy array, we can find out how many dimensions it has by accessing its `.ndim` attribute. The result is a number telling us how many dimensions it has.

For example, create a 2D Numpy array:

In [14]:
A = np.array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
A.ndim

2

The result tells us that `A` has 2 dimensions. The first dimension corresponds to the vertical direction counting the rows and the second dimension corresponds to the horizontal direction counting the columns.

We can find out how many rows and columns `A` has by accessing its `.shape` attribute:

In [16]:
A.shape

(3, 2)

The result is a tuple `(3,2)` of length 2 which means that `A` is a 2D array with 3 rows and 2 columns.

We can also find out how many entries `A` has in total by accessing its `.size` attribute:

In [17]:
A.size

6

This is the expected result since we know that `A` has 3 rows and 2 columns and therefore 2(3) = 6 total entries.


---


### Slicing and Indexing

Accessing the entries in an array is called *indexing* and accessing rows and columns (or subarrays) is called *slicing*. See the Numpy documentation for more information about [indexing and slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

Create a 1D Numpy array:

In [18]:
v = np.linspace(0,10,8)
print(v)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


Access the entries in a 1D array using the square brackets notation just like a Python list. For example, access the entry at index 3:

In [19]:
v[3]

4.285714285714286

Notice that Numpy array indices start at 0 just like Python sequences.

Create a 2D array of integers:

In [20]:
B = np.array([[6, 5, 3, 1, 1],[1, 0, 4, 0, 1],[5, 9, 2, 2, 9]])
print(B)

[[6 5 3 1 1]
 [1 0 4 0 1]
 [5 9 2 2 9]]


Access the entries in a 2D array using the square brackets with 2 indices. In particular, access the entry at row index 1 and column index 2:

In [21]:
B[1,2]

4

Access the top left entry in the array:

In [22]:
B[0,0]

6

Access the bottom right entry in the array:

In [23]:
B[-1,-1]

9

Access the row at index 2 using the colon `:` syntax:

In [24]:
B[2,:]

array([5, 9, 2, 2, 9])

Access the column at index 3:

In [25]:
B[:,3]

array([1, 0, 2])

Select the subarray of rows at index 1 and 2, and columns at index 2, 3 and 4:

In [26]:
subB = B[1:3,2:5]
print(subB)

[[4 0 1]
 [2 2 9]]


---

### Stacking

We can build bigger arrays out of smaller arrays by [stacking](https://docs.scipy.org/doc/numpy/user/quickstart.html#stacking-together-different-arrays) along different dimensions using the functions `numpy.hstack` and `numpy.vstack`.

Stack 3 different 1D Numpy arrays of length 3 vertically forming a 3 by 3 matrix:

In [27]:
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


Stack 1D Numpy arrays horizontally to create another 1D array:

In [28]:
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


### Exercise:
Use `numpy.hstack` and `numpy.vstack` to build the matrix $T$ where

$$
T = 
\begin{bmatrix}
1 & 0 & 5 & 5 \\ 
0 & 1 & 5 & 5 \\ 
1 & 2 & 4 & 5 \\ 
3 & 4 & 5 & 4
\end{bmatrix}
$$

In [29]:
A = np.eye(2)
B = 5 * np.ones((2,2))
C = np.array([[1,2],[3,4]])
D = B - A
A_B = np.hstack((A,B))
print(A_B)

[[1. 0. 5. 5.]
 [0. 1. 5. 5.]]


In [30]:
C_D = np.hstack((C,D))
print(C_D)

[[1. 2. 4. 5.]
 [3. 4. 5. 4.]]


In [31]:
T = np.vstack((A_B, C_D))
print(T)

[[1. 0. 5. 5.]
 [0. 1. 5. 5.]
 [1. 2. 4. 5.]
 [3. 4. 5. 4.]]


---
## Operations and Functions

### Array Operations

[Arithmetic operators](https://docs.scipy.org/doc/numpy/user/quickstart.html#basic-operations) including addition `+`, subtraction `-`, multiplication `*`, division `/` and exponentiation `**` are applied to arrays *elementwise*. For addition and substraction, these are the familiar vector/matrix operations we see in linear algebra:

In [32]:
A = np.array([[2,4],[6,8]])
B = np.array([[1,3],[5,7]])

In [33]:
A + B

array([[ 3,  7],
       [11, 15]])

In [34]:
A - B

array([[1, 1],
       [1, 1]])

In [35]:
A / B

array([[2.        , 1.33333333],
       [1.2       , 1.14285714]])

In [36]:
A * B

array([[ 2, 12],
       [30, 56]])

In [37]:
A ** 2

array([[ 4, 16],
       [36, 64]])

Notice that array multiplication and exponentiation are performed elementwise.

In Python 3.5+, the symbol `@` computes matrix multiplication for NumPy arrays:

In [38]:
A @ B

array([[22, 34],
       [46, 74]])

Alternatively, use `np.dot()`:

In [39]:
np.dot(A, B)

array([[22, 34],
       [46, 74]])

[Matrix powers](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.matrix_power.html) are performed by the function `numpy.linalg.matrix_power`:

In [40]:
from numpy.linalg import matrix_power as mpow

Compute $A^3$:

In [41]:
mpow(A,3)

array([[296, 432],
       [648, 944]])

Equivalently, use the `@` operator to compute $A^3$:

In [42]:
A @ A @ A

array([[296, 432],
       [648, 944]])

### Transpose

We can take the transpose of a matrix by using `.T`:

In [43]:
A

array([[2, 4],
       [6, 8]])

In [44]:
A.T

array([[2, 6],
       [4, 8]])

Or by using the numpy function `np.transpose()`:

In [45]:
np.transpose(A)

array([[2, 6],
       [4, 8]])

### Inverse
We can find the inverse of a square matrix by using the numpy function `np.linalg.inv()`:

In [46]:
np.linalg.inv(A)

array([[-1.  ,  0.5 ],
       [ 0.75, -0.25]])

### Trace
The trace is defined as the sum of all the diagonal entries of a matrix: $$\mathrm{Tr}(A) = \sum_i A_{i,i}$$
We can find the trace of a square matrix by using the numpy function `np.trace()`:

In [47]:
np.trace(A)

10

### Determinant
The determinant is defined as the product of all the eigenvalues of a matrix: $$\mathrm{det}|A| = \prod_i \lambda_i$$
We can find the determinant of a matrix by using the numpy function `np.linalg.det()`:

In [48]:
np.linalg.det(A)

-8.000000000000002

### Norm
We can find the norm of a matrix/vector by using the numpy function `np.linalg.norm()`. For more info check [doc](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html):

In [49]:
np.linalg.norm(A)

10.954451150103322

### Array Functions

There are *many* [array functions](https://docs.scipy.org/doc/numpy/reference/routines.html) we can use to compute with Numpy arrays. 

| | | |
| :---: | :---: | :---: |
| `numpy.sum` | `numpy.prod` | `numpy.mean` |
| `numpy.max` | `numpy.min` | `numpy.std` |
| `numpy.argmax` | `numpy.argmin` | `numpy.var` |

Create a 1D Numpy array with random values and compute:

In [50]:
arr = np.array([8,-2,4,7,-3])
print(arr)

[ 8 -2  4  7 -3]


Compute the mean of the values in the array:

In [51]:
np.mean(arr)

2.8

Find the index of the maximum element in the array:

In [52]:
max_i = np.argmax(arr)
print(max_i)

0


Verify the maximum value in the array:

In [53]:
np.max(arr)

8

In [54]:
arr[max_i]

8

Array functions apply to 2D arrays as well (and $N$-dimensional arrays in general) with the added feature that we can choose to apply array functions to the entire array, down the columns or across the rows (or any axis).

Create a 2D Numpy array with random values and compute the sum of all the entries:

In [55]:
M = np.array([[2,4,2],[2,1,1],[3,2,0],[0,6,2]])
print(M)

[[2 4 2]
 [2 1 1]
 [3 2 0]
 [0 6 2]]


In [56]:
np.sum(M)

25

The function `numpy.sum` also takes a keyword argument `axis` which determines along which dimension to compute the sum:

In [57]:
np.sum(M, axis=0) # Sum of the columns

array([ 7, 13,  5])

In [58]:
np.sum(M, axis=1) # Sum of the rows

array([8, 4, 5, 8])

---
## Random Number Generators

The subpackage `numpy.random` contains functions to generate Numpy arrays of [random numbers](https://docs.scipy.org/doc/numpy/reference/routines.random.html) sampled from different distributions. The following is a partial list of distributions:

| Function | Description |
| :--- | :--- |
| `numpy.random.rand(d1,...,dn)` | Create a NumPy array (with shape `(d1,...,dn)`) with entries sampled uniformly from `[0,1)` |
| `numpy.random.randn(d1,...,dn)` | Create a NumPy array (with shape `(d1,...,dn)`) with entries sampled from the standard normal distribution |
| `numpy.random.randint(a,b,size)` | Create a NumPy array (with shape `size`) with integer entries from `low` (inclusive) to `high` (exclusive) |

Sample a random number from the [uniform distribution](https://en.wikipedia.org/wiki/Uniform_distribution_%28continuous%29):

In [59]:
np.random.rand()

0.713476609615283

Sample 3 random numbers:

In [60]:
np.random.rand(3)

array([0.89336409, 0.46158008, 0.9377996 ])

Create 2D Numpy array of random samples:

In [61]:
np.random.rand(2,4)

array([[0.75183212, 0.39100241, 0.40811057, 0.463627  ],
       [0.94987011, 0.44173483, 0.34423244, 0.51168266]])

Random samples from the [standard normal distribution](https://en.wikipedia.org/wiki/Normal_distribution):

In [62]:
np.random.randn()

0.17116017786677504

In [63]:
np.random.randn(3)

array([-0.14468242, -2.8199465 , -0.39162501])

In [64]:
np.random.randn(3,1)

array([[-0.1157835 ],
       [ 0.31279795],
       [-1.87803489]])

Random integers sampled uniformly from various intervals:

In [65]:
np.random.randint(-10,10)

-6

In [66]:
np.random.randint(0,2,(4,8))

array([[0, 1, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 0]])

In [67]:
np.random.randint(-9,10,(5,2))

array([[ 7,  3],
       [-3,  0],
       [ 7, -5],
       [-1,  2],
       [ 3,  1]])

---
## Exercises

### Eigenvalues, Eigenvectors, and SVD decomposition
Consider the matrix $M$. $$M = \begin{bmatrix}
1 & 0 & 3 \\ 
3 & 7 & 2 \\ 
2 & -2 & 8 \\ 
0 & -1 & 1 \\
5 & 8 & 7
\end{bmatrix}$$

Using Numpy:
1. Compute its rank
2. Compute the eigen-values and eigen-vectors for matrices $M^TM$ and $MM^T$.
3. Find the SVD decomposition of $M$ and reconstruct it back to get the original $M$. Compare your results with your answers to the above problem and draw a conclusion.

In [69]:
# Compute rank
M = np.array([[1, 0, 3],
             [3, 7, 2],
             [2, -2, 8],
             [0, -1, 1],
             [5, 8, 7]])  # 5x3

print(M)
print()
print("Matrix M has rank: ", np.linalg.matrix_rank(M), "\n")

# Compute eigenvalues and eigenvectors for M^TM, MM^T
# Hint: Since both matrices are symmetric, use linalg.eigh() to compute eigenvalues and eigenvectors
S1, V1 = np.linalg.eigh(M.T @ M)
index = np.argsort(S1)[::-1]
S1 = S1[index]
V1 = V1[:, index]

S2, V2 = np.linalg.eigh(M @ M.T)
index = np.argsort(S2)[::-1]
S2 = S2[index]
V2 = V2[:, index]

print("The eigenvalues of M^TM are:\n", S1, "\n")
print("The eigenvectors of M^TM are:\n", V1, "\n")

print("The eigenvalues of MM^T are:\n", S2, "\n")
print("The eigenvectors of MM^T are:\n", V2, "\n")

[[ 1  0  3]
 [ 3  7  2]
 [ 2 -2  8]
 [ 0 -1  1]
 [ 5  8  7]]

Matrix M has rank:  2 

The eigenvalues of M^TM are:
 [2.14670489e+02 6.93295108e+01 8.12918346e-15] 

The eigenvectors of M^TM are:
 [[ 0.42615127  0.01460404  0.90453403]
 [ 0.61500884  0.72859799 -0.30151134]
 [ 0.66344497 -0.68478587 -0.30151134]] 

The eigenvalues of MM^T are:
 [ 2.14670489e+02  6.93295108e+01  5.27152149e-15  4.71798964e-16
 -4.32431417e-14] 

The eigenvectors of MM^T are:
 [[-0.16492942  0.24497323  0.09135579  0.05904992  0.94918577]
 [-0.47164732 -0.45330644  0.69954319  0.28321482 -0.04990773]
 [-0.33647055  0.82943965  0.32151809 -0.07951528 -0.29853121]
 [-0.00330585  0.16974659 -0.27906832  0.94207216 -0.07613197]
 [-0.79820031 -0.13310656 -0.56660431 -0.14993276 -0.04048003]] 



In [72]:
# SVD decomposition
# Hint! Use linalg.svd()
U, S, V_T = np.linalg.svd(M)
V = V_T.T

m, n = M.shape
M_recon = U[:, :n] @ np.diag(S) @ V_T[:m, :]
print(M_recon)

S_diag = np.zeros((m, n))
np.fill_diagonal(S_diag, S)


print("The SVD decomposition of M is defined as USV*T\n")
print("U is the left-singular vector:\n", U, "\n")
print("S is the singular values:\n", S_diag, "\n")
print("V is the right-singular vector:\n", V, "\n")

[[ 1.00000000e+00  7.51884549e-16  3.00000000e+00]
 [ 3.00000000e+00  7.00000000e+00  2.00000000e+00]
 [ 2.00000000e+00 -2.00000000e+00  8.00000000e+00]
 [-9.17536881e-18 -1.00000000e+00  1.00000000e+00]
 [ 5.00000000e+00  8.00000000e+00  7.00000000e+00]]
The SVD decomposition of M is defined as USV*T

U is the left-singular vector:
 [[-0.16492942 -0.24497323  0.9482579   0.09864471 -0.06214956]
 [-0.47164732  0.45330644 -0.02261948  0.08103373 -0.75165416]
 [-0.33647055 -0.82943965 -0.27341434 -0.18350729 -0.3006445 ]
 [-0.00330585 -0.16974659 -0.14522096  0.97468061  0.00915155]
 [-0.79820031  0.13310656 -0.06671416  0.00505374  0.58368021]] 

S is the singular values:
 [[1.46516378e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.32643446e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.99921582e-16]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]] 

V is the right-singular vector:
 [[-0.42615127  0.01460404 -0.90453403]
 [-0

### Conclusion
We can conclude from the results that the eigenvalue decomposition and the singular value decomposition are closely related. In fact, the singular value decomposition is a general approach that can be applied to any $mxn$ matrix, whereas eigevalue decomposition is more specific and can only be used for diagonalisable symmetric matrices.

We can evaluate the singular value decomposition using the following equations:

Given an SVD on a matrix $M$ we have:

$$M^TM = V\Sigma^TU^TU\Sigma V^T = V(\Sigma^T\Sigma)V^T$$
$$MM^T = U\Sigma V^TV\Sigma^TU^T = U(\Sigma\Sigma^T)U^T$$

In [75]:
assert np.all(np.isclose(M.T @ M, V @ S_diag.T @ S_diag @ V.T))
assert np.all(np.isclose(M @ M.T, U @ S_diag @ S_diag.T @ U.T))